const RATE_WINDOW = 60_000;
const RATE_MAX = 60;
const hits = new Map();
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"public, max-age=60",...extra}})}
function cors(origin="*"){return{"access-control-allow-origin":origin,"access-control-allow-methods":"GET,OPTIONS","access-control-allow-headers":"Content-Type, Accept"}}
function limited(ip){const now=Date.now(),e=hits.get(ip)||{n:0,t:now};if(now-e.t>RATE_WINDOW){e.n=0;e.t=now}e.n++;hits.set(ip,e);if(hits.size>3000&&Math.random()<.05)hits.delete(hits.keys().next().value);return e.n<=RATE_MAX}
async function fetchJSON(url){const req=new Request(url,{headers:{accept:"application/json"}}),cached=await caches.default.match(req);if(cached)return cached;const res=await fetch(req);if(res.ok)await caches.default.put(req,res.clone());return res}
async function rawg(path,env,params=new URLSearchParams()){if(!env.RAWG_API_KEY)throw new Error("RAWG_API_KEY secret is missing on the Worker");const u=new URL(`https://api.rawg.io/api${path}`);for(const [k,v] of params.entries())if(k!=="key")u.searchParams.set(k,v);u.searchParams.set("key",env.RAWG_API_KEY);return fetchJSON(u.toString())}
async function proxyRawg(req,env,path){const r=await rawg(path,env,new URL(req.url).searchParams),d=await r.json().catch(()=>({}));return json(d,r.status,cors())}
async function steam(path,env,params={}){if(!env.STEAM_API_KEY)return null;const u=new URL(`https://api.steampowered.com${path}`);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));u.searchParams.set("key",env.STEAM_API_KEY);return fetchJSON(u.toString())}
async function handle(req,env){const u=new URL(req.url),p=u.pathname.replace(/\/$/,"")||"/";
if(p==="/health")return json({ok:true,service:"progLog API proxy",time:new Date().toISOString()},200,cors());
if(p==="/games")return proxyRawg(req,env,"/games");
const gm=p.match(/^\/games\/(\d+)$/);if(gm)return proxyRawg(req,env,`/games/${gm[1]}`);
const sub=p.match(/^\/games\/(\d+)\/(achievements|additions|screenshots|movies|stores|reddit|development-team|game-series|parent-games|suggested|twitch|youtube)$/);if(sub)return proxyRawg(req,env,`/games/${sub[1]}/${sub[2]}`);
if(p==="/steam/resolve"){if(!env.STEAM_API_KEY)return json({available:false,error:"Steam integration is optional and is not configured."},503,cors());const vanity=u.searchParams.get("vanity");if(!vanity)return json({error:"vanity is required"},400,cors());const r=await steam("/ISteamUser/ResolveVanityURL/v1/",env,{vanityurl:vanity}),d=await r.json().catch(()=>({}));return json(d,r.status,cors())}
if(p==="/steam/player"){if(!env.STEAM_API_KEY)return json({available:false,error:"Steam integration is optional and is not configured."},503,cors());const steamid=u.searchParams.get("steamid");if(!steamid)return json({error:"steamid is required"},400,cors());const r=await steam("/ISteamUser/GetPlayerSummaries/v2/",env,{steamids:steamid}),d=await r.json().catch(()=>({}));return json(d,r.status,cors())}
if(p==="/steam/owned"){if(!env.STEAM_API_KEY)return json({available:false,error:"Steam integration is optional and is not configured."},503,cors());const steamid=u.searchParams.get("steamid");if(!steamid)return json({error:"steamid is required"},400,cors());const r=await steam("/IPlayerService/GetOwnedGames/v0001/",env,{steamid,include_appinfo:"true",include_played_free_games:"true",format:"json"}),d=await r.json().catch(()=>({}));return json(d,r.status,cors())}
if(p==="/steam/recent"){if(!env.STEAM_API_KEY)return json({available:false,error:"Steam integration is optional and is not configured."},503,cors());const steamid=u.searchParams.get("steamid");if(!steamid)return json({error:"steamid is required"},400,cors());const r=await steam("/IPlayerService/GetRecentlyPlayedGames/v0001/",env,{steamid,count:"20",format:"json"}),d=await r.json().catch(()=>({}));return json(d,r.status,cors())}
if(p==="/steam/schema"){if(!env.STEAM_API_KEY)return json({available:false,error:"Steam integration is optional and is not configured."},503,cors());const appid=u.searchParams.get("appid");if(!appid)return json({error:"appid is required"},400,cors());const r=await steam("/ISteamUserStats/GetSchemaForGame/v2/",env,{appid,format:"json"}),d=await r.json().catch(()=>({}));return json(d,r.status,cors())}
if(p==="/steam/achievements"){if(!env.STEAM_API_KEY)return json({available:false,error:"Steam integration is optional and is not configured."},503,cors());const steamid=u.searchParams.get("steamid"),appid=u.searchParams.get("appid");if(!steamid||!appid)return json({error:"steamid and appid are required"},400,cors());const r=await steam("/ISteamUserStats/GetPlayerAchievements/v1/",env,{steamid,appid,l:"english",format:"json"}),d=await r.json().catch(()=>({}));return json(d,r.status,cors())}
return json({error:"Not found"},404,cors())}
export default{async fetch(req,env){if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors()});if(req.method!=="GET")return json({error:"Method not allowed"},405,cors());const ip=req.headers.get("CF-Connecting-IP")||"unknown";if(!limited(ip))return json({error:"Rate limit exceeded. Try again in a minute."},429,cors());try{return await handle(req,env)}catch(e){return json({error:e?.message||"Worker error"},500,cors())}}};
